### ISSUE TITLE
Executable fails to build with `optparse-applicaitve >= 0.18`

### ISSUE THREAD

**Issue by hololeap** [ennocramer/floskell#77]
There are various errors, such as:

```
src/main/Main.hs:70:14: error:
    Not in scope: ‘PP.displayIO’
    Module ‘Options.Applicative.Help.Pretty’ does not export ‘displayIO’.
   |
70 |         then PP.displayIO stdout . PP.renderPretty 1.0 80 $
   |              ^^^^^^^^^^^^
```

---

From the [`optparse-applicative` changelog](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/changelog):

> Move to `prettyprinter` library for pretty printing.
> 
> This is a potentially breaking change when one uses the `*Doc` family of functions (like `headerDoc`) from `Options.Applicative`. However, as versions of `ansi-wl-pprint > 1.0` export a compatible `Doc` type, this can be mitigated by using a recent version.
> 
> One can also either import directly from `Options.Applicative.Help` or from the `Prettyprinter` module of `prettyprinter`.

---

Full build log: https://gist.github.com/hololeap/5df44b5ce636deade4e5985033296786

**Comment by ennocramer** [comment]
This problem has been addressed with `floskell-0.11.0`.
